language: node_js
sudo: true

node_js:
  - "8"

env:
  - BROWSER=true

cache:
  directories:
  - node_modules

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  # - npm install -g yarn
  # - yarn

script:
  - npm run build:site
  # - npm run test:coverage
  - BROWSER=true COVERAGE=false FLAKEY=false npm run test:karma
  # - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info

after_success:
  - cd "$TRAVIS_BUILD_DIR"
  -  git init
  -  git checkout -b gh-pages
  -  git add -f .\siteoutput
  -  git -c user.name='travis' -c user.email='travis' commit -m "Update docs"
  - git push -f -q "https://${GH_TOKEN}@github.com/NervJS/at-ui-nerv" master:master
  # - git add .
  # - git commit -m "Update docs"
  # - git push  --quiet "https://${GH_TOKEN}@at-ui-nerv" master:master