language: node_js
sudo: false

node_js:
  - "8"

env:
  - BROWSER=true

cache:
  directories:
  - node_modules

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  # - npm install -g yarn
  # - yarn

script:
  - npm run build:site
  # - npm run test:coverage
  # - BROWSER=true COVERAGE=false FLAKEY=false npm run test:karma
  # - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info

after_script:
  - git add .
  - git commit -m "Update docs"
  - git push  --quiet "https://${GH_TOKEN}@at-ui-nerv" master:master