language: node_js
sudo: false

node_js:
  - "8"

env:
  - BROWSER=true

cache:
  directories:
  - node_modules

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g yarn
  - yarn

script:
  # - npm run lint
  - BROWSER=true COVERAGE=true FLAKEY=false npm run test:karma
  - npm run build:site
  # - npm run test:coverage
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info

after_script:
  - cd siteoutput
  - git init
  - git add .
  - git commit -m "Update Document"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages


# branches:
#   only:
#     - master
  